### ISSUE TITLE
Something is wrong with the names of the pdf's

### ISSUE THREAD

**Issue by alexismellamo** [AngelGallegosE/Osiris#12]
<img width="242" alt="screen shot 2017-03-13 at 6 07 36 pm" src="https://cloud.githubusercontent.com/assets/11366687/23880243/0483072c-0818-11e7-833e-f8e9ca44cba3.png">

**Comment by alexismellamo** [comment]
`url.slice(url.indexOf('//') + 2, url.indexOf('.com'))` this is not enough in some cases

**Comment by alexismellamo** [comment]
I mean, the name in www.vim.com sucks, and I don't think I even need to mention the one in www.npr.org

**Comment by abrophy** [comment]
What would be the preferred name structure?

OsirisPDF/<domain>/<rest of path with / replaced with . >.pdf?

or just < full address with / replaced with another character >.pdf ?

You'd still get crazy filenames for certain URLS, but it would be more clear for the end user and have at least some sort of organization

**Comment by alexismellamo** [comment]
Hi @abrophy, thanks for commenting

I think I would like to see something like '<domain without http thing>_<the other part of the url but / replaced with _>.pdf'

In `https://github.com/AngelGallegosE/Osiris/issues/12` the expected name would be `github.com_AngelGalledoE_Osiris_issues_12`

Does that make sense?

**Comment by AngelGallegosE** [comment]
https://github.com/AngelGallegosE/Osiris/pull/19
