### ISSUE TITLE
General progress bar of all the links that are being downloaded 

### ISSUE THREAD

**Issue by AngelGallegosE** [AngelGallegosE/Osiris#13]
![image](https://cloud.githubusercontent.com/assets/12789122/23880352/ba39baa2-0818-11e7-9b5c-60c2a5fe7712.png)

**Comment by alexismellamo** [comment]
Maybe we can use https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress

**Comment by AngelGallegosE** [comment]
https://github.com/AngelGallegosE/Osiris/pull/22
