### ISSUE TITLE
Open button for each pdf generated 

### ISSUE THREAD

**Issue by alexismellamo** [AngelGallegosE/Osiris#17]
Maybe something like this?
![image](https://cloud.githubusercontent.com/assets/11366687/23881127/04599d28-081e-11e7-8142-2f21dbb4ef22.png)

**Comment by noelrock333** [comment]
Maybe a preview window would be great

**Comment by AngelGallegosE** [comment]
https://github.com/AngelGallegosE/Osiris/pull/56
