### ISSUE TITLE
When a pdf is ready, the "loading" message disappear in all urls D:

### ISSUE THREAD

**Issue by alexismellamo** [AngelGallegosE/Osiris#24]
😠 😡 
<img width="725" alt="screen shot 2017-03-15 at 3 22 25 pm" src="https://cloud.githubusercontent.com/assets/11366687/23971403/6e9d535c-0993-11e7-9173-87364e18fb32.png">

**Comment by alexismellamo** [comment]
Should be a loading in `vim.org/index`

**Comment by AngelGallegosE** [comment]
Working on it

**Comment by AngelGallegosE** [comment]
https://github.com/AngelGallegosE/Osiris/pull/54
