### ISSUE TITLE
Is this file trash?

### ISSUE THREAD

**Issue by alexismellamo** [AngelGallegosE/Osiris#49]
<img width="976" alt="screen shot 2017-03-19 at 2 49 08 am" src="https://cloud.githubusercontent.com/assets/11366687/24079484/ab05f57a-0c4e-11e7-9e4a-47ecf54c3a29.png">

**Comment by AngelGallegosE** [comment]
Yea, it is. I should have deleted it before commit, sorry. I'll deleted it in the next commit.

**Comment by alexismellamo** [comment]
https://github.com/AngelGallegosE/Osiris/pull/53
