### ISSUE TITLE
When there's only one url the app crash

### ISSUE THREAD

**Issue by alexismellamo** [AngelGallegosE/Osiris#51]
<img width="799" alt="screen shot 2017-03-19 at 3 19 33 am" src="https://cloud.githubusercontent.com/assets/11366687/24079690/36342316-0c53-11e7-8a16-7a2d54ac4012.png">

**Comment by alexismellamo** [comment]
never download the pdf
<img width="798" alt="screen shot 2017-03-19 at 3 23 46 am" src="https://cloud.githubusercontent.com/assets/11366687/24079700/9987c10c-0c53-11e7-8e6c-e2a43d6499e1.png">

**Comment by AngelGallegosE** [comment]
Working on it
